### ISSUE TITLE
missing common mark module

### ISSUE THREAD

**Issue by schultzh** [GatorEducator/gatorgrader#153]
I cannot currently use Gradlee Grade effectively on my personal laptop. I am receiving the following errors: 

```
"Traceback (most recent call last):
  File "/Users/hannahschultz/.local/share/gatorgrader/gatorgrader.py", line 5, in <module>
    from gator import orchestrate
  File "/Users/hannahschultz/.local/share/gatorgrader/gator/orchestrate.py", line 11, in <module>
    from gator import invoke  # noqa: F401
  File "/Users/hannahschultz/.local/share/gatorgrader/gator/invoke.py", line 6, in <module>
    from gator import fragments
  File "/Users/hannahschultz/.local/share/gatorgrader/gator/fragments.py", line 6, in <module>
    import commonmark
ModuleNotFoundError: No module named 'commonmark'"
```

This error repeats for each check within the repository. I assume that it is something my laptop is missing, however, I wanted to bring it up and make sure.

**Comment by Michionlion** [comment]
You need to either update the version of GatorGradle in your `build.gradle` to `0.3.3` or higher, or delete the `~/.local/share/gatorgrader` directory.

**Comment by schultzh** [comment]
How would I update the ```build.gradle``` ?

**Comment by Michionlion** [comment]
Find the line that specifies the version of GatorGradle -- look in the [documentation](https://github.com/GatorEducator/gatorgradle#including-gatorgradle-in-your-project) for more specifics -- and change it to `0.4.0`.
