### ISSUE TITLE
"gradle grade" Command Failing on Ubuntu 18.04

### ISSUE THREAD

**Issue by durcij** [GatorEducator/gatorgrader#213]
**Describe the bug**

When attempting to run the `gradle grade` command, there is an error that prevents it from properly installing the needed dependencies.

**To Reproduce**

1. Open a lab directory on a lab machine
2. Attempt to run `gradle grade`

**Expected behavior**

I had expected that it would run correctly, and provide me with the feedback about my lab.

**Environment**

I was running this from the lab machines, which I'd assume should have all of the necessary programs properly updated and installed.

**Additional context**

Below is the exact output of my attempts to run GatorGrader:

```
durcij@aldenv153:~/cs301S2020/lab01-durcij$ gradle grade

> Configure project :
Configured GatorGradle 0.5.1

> Task :grade
Installing GatorGrader...
Cloning into '/home/d/durcij/.local/share/gatorgrader'...
Checking out to 'master'
Pulling branch...
Updated!
Managing GatorGrader's Python dependencies...
ERROR: GatorGrader management failed, could not install dependencies!
Command run: [pipenv sync --bare]
OUTPUT: Installing dependencies from Pipfile.lock (6f7f45)...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/cli.py", line 1049, in sync
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 2518, in do_sync
    system=system,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 807, in do_install_dependencies
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
Deleting /home/d/durcij/.local/share/gatorgrader

> Task :grade FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grade'.
> GatorGrader management failed; see above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
1 actionable task: 1 executed
```

**Comment by Michionlion** [comment]
Hmmm... this is extremely similar to a bug we dealt with a while ago that related to python versions. Do you by chance have `pyenv` installed on your lab machine account?

Also, can you try deleting the `$HOME/.local/share/gatorgrader` folder?

**Comment by gkapfham** [comment]
Hello @durcij, can you please delete the `gatorgrader` and `virtualenvs` directories inside of the `.local/share/` directory on your Ubuntu 18.04 desktop? There was recently an upgrade in the dependencies for GatorGrader and it is possible that you might need to delete and previously installed versions of GatorGrader and any of the virtual environments that it created and then let the `gradle grade` command install everything again.

@durcij can you please report back so that @alexheinle and I can help you to fully resolve this issue?

Finally, thanks @Michionlion for reponding and getting the discussion started!

**Comment by durcij** [comment]
Thanks for responding @Michionlion and @gkapfham .  I'll make sure to try deleting the old dependencies next time I work at a lab computer.

**Comment by gkapfham** [comment]
Hi @durcij do you have any updates on this issue?

**Comment by durcij** [comment]
Yes, sorry for the delay.  I deleted the `virtualenvs` folder, but couldn't find the `gatorgrader` folder you'd listed.

The output after removing the folder was as follows:

```
durcij@aldenv153:~/cs301S2020/lab01-durcij$ gradle grade
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :
Configured GatorGradle 0.5.1

> Task :grade
Installing GatorGrader...
Cloning into '/home/d/durcij/.local/share/gatorgrader'...
Checking out to 'master'
Pulling branch...
Updated!
Managing GatorGrader's Python dependencies...
ERROR: GatorGrader management failed, could not install dependencies!
Command run: [pipenv sync --bare]
OUTPUT: Creating a virtualenv for this project...
Pipfile: /home/d/durcij/.local/share/gatorgrader/Pipfile
Using /usr/bin/python3 (3.6.9) to create virtualenv...
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/d/durcij/.local/share/virtualenvs/gatorgrader-kmIgBwc8/bin/python3
Also creating executable in /home/d/durcij/.local/share/virtualenvs/gatorgrader-kmIgBwc8/bin/python
Installing setuptools, pip, wheel...done.
Setting project for gatorgrader-kmIgBwc8 to /home/d/durcij/.local/share/gatorgrader

Virtualenv location: /home/d/durcij/.local/share/virtualenvs/gatorgrader-kmIgBwc8
Installing dependencies from Pipfile.lock (6f7f45)...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/cli.py", line 1049, in sync
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 2518, in do_sync
    system=system,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 807, in do_install_dependencies
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
Deleting /home/d/durcij/.local/share/gatorgrader

> Task :grade FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grade'.
> GatorGrader management failed; see above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
1 actionable task: 1 executed
```

**Comment by Michionlion** [comment]
Can you report the version of Pip (`pip --version`) and Pipenv (`pipenv --version`)?

**Comment by durcij** [comment]
`pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)`
`pipenv, version 2018.7.1`

**Comment by Michionlion** [comment]
Can you try upgrading Pip with `pip install --upgrade pip`? I think that may be the problem in this case. The version of Python Pip is attached to shouldn't matter, I think. For context, here is my (working) versions:
```
$ pip --version && pipenv --version
pip 20.0.2 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
pipenv, version 2018.11.26
```

**Comment by durcij** [comment]
I ran the command, and pip updated, but it's still giving me the error when I try to run `gradle grade`.

**Comment by alexheinle** [comment]
After running gradle grade, the terminal is now showing a different error message than what @durcij showed.

```
heinlea@aldenv153:~/cs302s2019/computer-science-302-spring-2019-lab-3-alexheinle$ gradle grade

Welcome to Gradle 6.1.1!

Here are the highlights of this release:
 - Reusable dependency cache
 - Configurable compilation order between Groovy/Kotlin/Java/Scala
 - New sample projects in Gradle's documentation

For more details see https://docs.gradle.org/6.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :grade
Updating GatorGrader...
From https://github.com/GatorEducator/gatorgrader
   c099fea..64562e0  argument/optional-advanced-tag -> origin/argument/optional-advanced-tag
   bbfdffb..1247c04  documentation/new-features -> origin/documentation/new-features
 * [new tag]         v1.0.4     -> v1.0.4
Already up to date.


Warning: Nashorn engine is planned to be removed from a future JDK release
'/home/h/heinlea/.local/share/virtualenvs/gatorgrader-bI7zswEt/bin/python' '/home/h/heinlea/.local/share/gatorgrader/gatorgrader.py' '--nowelcome' '--json' '--commits' '15' produced unparsable json: Failed to parse json -- <eval>:3:52 Missing close quote
Use --help to show details about GatorGrader's use.)
                                                    ^ in <eval> at line number 3 at column number 52:
"Incorrect command-line arguments.

Use --help to show details about GatorGrader's use."
Incorrect command-line arguments.

Use --help to show details about GatorGrader's use.
Warning: Nashorn engine is planned to be removed from a future JDK release
'/home/h/heinlea/.local/share/virtualenvs/gatorgrader-bI7zswEt/bin/python' '/home/h/heinlea/.local/share/gatorgrader/gatorgrader.py' '--nowelcome' '--json' '--directory' 'src/www/' '--file' 'index.html' '--fragment' '<body>' '--count' '1' '--exact' produced unparsable json: Failed to parse json -- <eval>:3:52 Missing close quote
Use --help to show details about GatorGrader's use.)
                                                    ^ in <eval> at line number 3 at column number 52:
"Incorrect command-line arguments.

Use --help to show details about GatorGrader's use."
Incorrect command-line arguments.

Use --help to show details about GatorGrader's use.
Warning: Nashorn engine is planned to be removed from a future JDK release
'/home/h/heinlea/.local/share/virtualenvs/gatorgrader-bI7zswEt/bin/python' '/home/h/heinlea/.local/share/gatorgrader/gatorgrader.py' '--nowelcome' '--json' '--directory' 'src/www/' '--file' 'index.html' '--fragment' 'github.css' '--count' '1' '--exact' produced unparsable json: Failed to parse json -- <eval>:3:52 Missing close quote
Use --help to show details about GatorGrader's use.)
                                                    ^ in <eval> at line number 3 at column number 52:
"Incorrect command-line arguments.

Use --help to show details about GatorGrader's use."
Incorrect command-line arguments.

Use --help to show details about GatorGrader's use.
Warning: Nashorn engine is planned to be removed from a future JDK release
'/home/h/heinlea/.local/share/virtualenvs/gatorgrader-bI7zswEt/bin/python' '/home/h/heinlea/.local/share/gatorgrader/gatorgrader.py' '--nowelcome' '--json' '--directory' 'src/www/' '--file' 'index.html' '--fragment' '<time>' '--count' '5' produced unparsable json: Failed to parse json -- <eval>:3:52 Missing close quote
Use --help to show details about GatorGrader's use.)
                                                    ^ in <eval> at line number 3 at column number 52:
"Incorrect command-line arguments.

Use --help to show details about GatorGrader's use."
Incorrect command-line arguments.

Use --help to show details about GatorGrader's use.
Warning: Nashorn engine is planned to be removed from a future JDK release
'/home/h/heinlea/.local/share/virtualenvs/gatorgrader-bI7zswEt/bin/python' '/home/h/heinlea/.local/share/gatorgrader/gatorgrader.py' '--nowelcome' '--json' '--directory' 'src/www/' '--file' 'index.html' '--fragment' '<h1>Share Your Travels</h1>' '--count' '1' '--exact' produced unparsable json: Failed to parse json -- <eval>:3:52 Missing close quote
Use --help to show details about GatorGrader's use.)
                                                    ^ in <eval> at line number 3 at column number 52:
"Incorrect command-line arguments.

Use --help to show details about GatorGrader's use."
Incorrect command-line arguments.

Use --help to show details about GatorGrader's use.
Warning: Nashorn engine is planned to be removed from a future JDK release
'/home/h/heinlea/.local/share/virtualenvs/gatorgrader-bI7zswEt/bin/python' '/home/h/heinlea/.local/share/gatorgrader/gatorgrader.py' '--nowelcome' '--json' '--directory' 'writing' '--file' 'reflection.md' '--words' '100' produced unparsable json: Failed to parse json -- <eval>:3:52 Missing close quote
Use --help to show details about GatorGrader's use.)
                                                    ^ in <eval> at line number 3 at column number 52:
"Incorrect command-line arguments.

Use --help to show details about GatorGrader's use."
Incorrect command-line arguments.

Use --help to show details about GatorGrader's use.
Warning: Nashorn engine is planned to be removed from a future JDK release
'/home/h/heinlea/.local/share/virtualenvs/gatorgrader-bI7zswEt/bin/python' '/home/h/heinlea/.local/share/gatorgrader/gatorgrader.py' '--nowelcome' '--json' '--directory' 'src/www/' '--file' 'index.html' '--fragment' '<html>' '--count' '1' '--exact' produced unparsable json: Failed to parse json -- <eval>:3:52 Missing close quote
Use --help to show details about GatorGrader's use.)
                                                    ^ in <eval> at line number 3 at column number 52:
"Incorrect command-line arguments.

Use --help to show details about GatorGrader's use."
Incorrect command-line arguments.

Use --help to show details about GatorGrader's use.
Warning: Nashorn engine is planned to be removed from a future JDK release
'/home/h/heinlea/.local/share/virtualenvs/gatorgrader-bI7zswEt/bin/python' '/home/h/heinlea/.local/share/gatorgrader/gatorgrader.py' '--nowelcome' '--json' '--directory' 'images' '--file' 'travels_submission.png' '--exists' produced unparsable json: Failed to parse json -- <eval>:3:52 Missing close quote
Use --help to show details about GatorGrader's use.)
                                                    ^ in <eval> at line number 3 at column number 52:
"Incorrect command-line arguments.

Use --help to show details about GatorGrader's use."
Incorrect command-line arguments.

```

**Comment by Michionlion** [comment]
The Nashorn warning was only present on older versions of GatorGradle -- are you running `0.5.0`? Check the `build.gradle` file.

**Comment by Michionlion** [comment]
Closing as this issue appears to be resolved.
